export const AUTHENTICATION_SIGNIN_REQUEST = 'AUTHENTICATION_SIGNIN_REQUEST'
export const AUTHENTICATION_SIGNIN_SUCCESS = 'AUTHENTICATION_SIGNIN_SUCCESS'
export const AUTHENTICATION_SIGNIN_FAILED = 'AUTHENTICATION_SIGNIN_FAILED'

export const AUTHENTICATION_CHECK_STATE_REQUEST =
  'AUTHENTICATION_CHECK_STATE_REQUEST'
export const AUTHENTICATION_CHECK_STATE_SUCCESS =
  'AUTHENTICATION_CHECK_STATE_SUCCESS'
export const AUTHENTICATION_CHECK_STATE_FAILED =
  'AUTHENTICATION_CHECK_STATE_FAILED'
